title : My Notes
name: '김용범 의 작업노트'
description: 'Pytorch Django and TypeScript'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  book:
    title: Book
    default_open: false
    output: true
  javascript:
    title: JS
    default_open: false
    output: true
  python:
    title: Python
    default_open: false
    output: true
  sql:
    title: SQL
    default_open: false
    output: true
  ubuntu:
    title: Ubuntu
    default_open: false
    output: true
  news:
    title: News
    default_open: false
    output: true
  posts:
    title: Essays
    default_open: false
    output: true

defaults:
  - scope:
      type: book
    values:
      title: Book Review
      permalink: /book/:title
  - scope:
      type: js
    values:
      title: JavaScript & TypeScript
      permalink: /js/:title
  - scope:
      type: python
    values:
      title: Machine Learning of Python
      permalink: /python/:title
  - scope:
      type: sql
    values:
      title: SQL
      permalink: /sql/:title
  - scope:
      type: ubuntu
    values:
      title: Ubuntu
      permalink: /ubuntu/:title
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: News
      permalink: /news/:title

plugins:
  - jekyll-sitemap