title : My Notes
name: '김용범 의 작업노트'
description: 'Pytorch Django and TypeScript'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

# Markdown Processing
kramdown:
  input: GFM
  math_engine: mathjax

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  book:
    title: 도서리뷰
    default_open: false
    output: true
  blog:
    title: 취미,일상
    default_open: false
    output: true
  finance:
    title: 금융투자
    default_open: false
    output: true
  ubuntu:
    title: 우분투 DB
    default_open: false
    output: true
  python:
    title: 파이썬
    default_open: false
    output: true
  js:
    title: 자바스크립트
    default_open: false
    output: true

defaults:
  - scope:
      type: book
    values:
      title: Book Review
      permalink: /book/:title
  - scope:
      type: blog
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: finance
    values:
      title: Stock
      permalink: /stock/:title
  - scope:
      type: js
    values:
      title: JavaScript & TypeScript
      permalink: /js/:title
  - scope:
      type: python
    values:
      title: Machine Learning of Python
      permalink: /python/:title

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji