title : My Notes
name: '김용범 의 작업노트'
description: 'Pytorch Django and TypeScript'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

# Markdown Processing
kramdown:
  input: GFM
  math_engine: mathjax

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  00ml:
    title: Machine Learning (ML)
    default_open: false
    output: true
  01js:
    title: FrontEnd (Ts)
    default_open: false
    output: true
  02django:
    title: BackEnd (Django,Nginx)
    default_open: false
    output: true
  03python:
    title: Python
    default_open: false
    output: true
  04ubuntu:
    title: Ubuntu
    default_open: false
    output: true
  05stock:
    title: 금융투자
    default_open: false
    output: true
  06contents:
    title: 리뷰 및 후기
    default_open: false
    output: true
  07posts:
    title: 기타
    default_open: false
    output: true

defaults:
  - scope:
      type: 01js
    values:
      title: JavaScript & TypeScript
      permalink: /js/:title
  - scope:
      type: 02django
    values:
      title: Fullstack with Django
      permalink: /django/:title
  - scope:
      type: 03python
    values:
      title: Django, Machine Learning of Python
      permalink: /python/:title
  - scope:
      type: 04ubuntu
    values:
      title: ubuntu server and db
      permalink: /ubuntu/:title
  - scope:
      type: 05stock
    values:
      title: Kospi Kosdaq Market
      permalink: /stock/:title
  - scope:
      type: 06contents
    values:
      title: Movie Book Review
      permalink: /contents/:title
  - scope:
      type: 07posts
    values:
      title: Essays
      permalink: /posts/:title

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji