title : My Notes
name: '김용범 의 작업노트'
description: 'Pytorch Django and TypeScript'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

# Markdown Processing
kramdown:
  input: GFM
  math_engine: mathjax

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  item01js:
    title: 프론트엔드
    default_open: false
    output: true
  item02python:
    title: 파이썬
    default_open: false
    output: true
  item03ubuntu:
    title: 우분투 서버
    default_open: false
    output: true
  item04stock:
    title: 금융투자
    default_open: false
    output: true
  item05contents:
    title: 영화 도서리뷰
    default_open: false
    output: true
  item06posts:
    title: 취미 및 기타
    default_open: false
    output: true

defaults:
  - scope:
      type: item01js
    values:
      title: JavaScript & TypeScript
      permalink: /item01js/:title
  - scope:
      type: item02python
    values:
      title: Django, Machine Learning of Python
      permalink: /item02python/:title
  - scope:
      type: item03ubuntu
    values:
      title: ubuntu server and db
      permalink: /item03ubuntu/:title
  - scope:
      type: item04stock
    values:
      title: Kospi Kosdaq Market
      permalink: /item04stock/:title
  - scope:
      type: item05contents
    values:
      title: Movie Book Review
      permalink: /item05contents/:title
  - scope:
      type: item06posts
    values:
      title: Essays
      permalink: /item06posts/:title

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji